name: Firebase Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs_on: ubuntu-latest
    steps:
      - name: Checkout Repo
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "14.x"
      - name: Install Dependencies
      - run: npm ci
      - name: Run Tests
      - run: npm test
      - name: Build
      - run: npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
