name: Node Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run start:dev &
      - run: npm test
      - run: npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --project tdd-cse-4283-staging --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
